version: '3.9'

services:
  postgres:
    container_name: llamagator_postgres
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
